# Generated by Django 2.1.4 on 2021-09-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0007_remove_setmeal_app'),
        ('users', '0008_devices_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='订单编号')),
                ('state', models.SmallIntegerField(choices=[(0, '订阅成功'), (1, '支付成功'), (2, '订阅取消'), (3, '支付但取消')], db_index=True, default=0, verbose_name='状态')),
                ('order_type', models.IntegerField(choices=[(0, '沙箱'), (1, '正式')], db_index=True, default=0, verbose_name='订单类型')),
                ('refund_time', models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='退单时间')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=128, null=True, verbose_name='国家')),
                ('product_time', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='订单时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPackage', verbose_name='APP平台')),
                ('set_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.SetMeal', verbose_name='套餐')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order',
            },
        ),
    ]
