# Generated by Django 2.1.4 on 2021-09-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210916_0939'),
        ('orders', '0002_auto_20210916_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Devices', verbose_name='设备平台'),
        ),
    ]
