# Generated by Django 2.1.4 on 2021-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='用户ID'),
        ),
    ]
