# Generated by Django 2.1.4 on 2021-09-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210922_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='devices',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='设备ID'),
        ),
    ]
