# Generated by Django 2.1.4 on 2021-09-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210922_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='devices',
            new_name='device_id',
        ),
    ]
