# Generated by Django 2.1.4 on 2021-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210922_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='device_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='package_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, unique=True, verbose_name='AppID'),
        ),
    ]
