# Generated by Django 2.1.4 on 2021-12-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0008_shareconfig'),
        ('orders', '0008_auto_20210923_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='商品ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='名称')),
                ('type', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='类型')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, verbose_name='分类')),
                ('image_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='图片链接')),
                ('home_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='主页链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('plan_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='计划ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='描述')),
                ('billing_number', models.IntegerField(default=0, verbose_name='计费周期次数')),
                ('currency_code', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='货币单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Product', verbose_name='商品')),
                ('set_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.SetMeal', verbose_name='套餐')),
            ],
            options={
                'verbose_name': '商品计划',
                'verbose_name_plural': '商品计划',
                'db_table': 'ProductPlan',
            },
        ),
    ]
