# Generated by Django 2.1.4 on 2022-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户IP')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户国家')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户城市')),
                ('node_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='节点ip')),
                ('node_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='节点名称')),
                ('ping_result', models.BooleanField(choices=[(0, '成功'), (1, '失败')], db_index=True, default=1, verbose_name='ping结果')),
                ('connect_result', models.BooleanField(choices=[(0, '成功'), (1, '失败')], db_index=True, default=1, verbose_name='连接结果')),
                ('connect_time', models.DateTimeField(blank=True, null=True, verbose_name='连接时间')),
                ('dev_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备名称')),
                ('network', models.CharField(blank=True, max_length=128, null=True, verbose_name='网络')),
                ('operator', models.CharField(blank=True, max_length=128, null=True, verbose_name='运营商')),
            ],
            options={
                'verbose_name': '连接记录表',
                'verbose_name_plural': '连接记录表',
            },
        ),
        migrations.CreateModel(
            name='PingFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户IP')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户国家')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户城市')),
                ('node_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='节点ip')),
                ('node_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='节点名称')),
                ('ping_return', models.CharField(blank=True, max_length=128, null=True, verbose_name='ping返回值')),
                ('ping_result', models.BooleanField(choices=[(0, '成功'), (1, '失败')], db_index=True, default=1, verbose_name='ping结果')),
                ('ping_time', models.DateTimeField(blank=True, null=True, verbose_name='ping时间')),
            ],
            options={
                'verbose_name': 'ping反馈表',
                'verbose_name_plural': 'ping反馈表',
            },
        ),
    ]
