# Generated by Django 2.1.4 on 2022-06-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pingfeedback',
            old_name='ping_return',
            new_name='ping_value',
        ),
    ]
