# Generated by Django 2.1.4 on 2022-06-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20220601_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingfeedback',
            name='ping_value',
        ),
        migrations.AddField(
            model_name='linkagerecord',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='pingfeedback',
            name='ping_val1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ping返回值1'),
        ),
        migrations.AddField(
            model_name='pingfeedback',
            name='ping_val2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ping返回值2'),
        ),
        migrations.AddField(
            model_name='pingfeedback',
            name='ping_val3',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ping返回值3'),
        ),
        migrations.AddField(
            model_name='pingfeedback',
            name='user_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户城市'),
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户国家'),
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='node_ip',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='节点ip'),
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='node_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='user_ip',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户IP'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户城市'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户国家'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='node_ip',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='节点ip'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='node_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='ping_result',
            field=models.BooleanField(choices=[(0, '成功'), (1, '失败')], default=1, verbose_name='ping结果'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='user_ip',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户IP'),
        ),
    ]
