# Generated by Django 2.1.4 on 2022-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220602_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('switch', models.BooleanField()),
                ('comment', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'api开关',
                'verbose_name_plural': 'api开关',
            },
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='connect_result',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], db_index=True, default=1, verbose_name='连接结果'),
        ),
        migrations.AlterField(
            model_name='linkagerecord',
            name='ping_result',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], db_index=True, default=1, verbose_name='ping结果'),
        ),
        migrations.AlterField(
            model_name='pingfeedback',
            name='ping_result',
            field=models.IntegerField(choices=[(1, '成功'), (0, '失败')], db_index=True, default=1, verbose_name='ping结果'),
        ),
    ]
