# Generated by Django 2.1.4 on 2021-09-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, unique=True, verbose_name='uuid')),
                ('package_id', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, unique=True, verbose_name='App_id')),
                ('flow', models.FloatField(blank=True, db_index=True, default=0, verbose_name='已用流量(单位:GB)')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.BigIntegerField(db_index=True, default=0, unique=True, verbose_name='uid')),
                ('email', models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='用户密码')),
                ('member_validity_time', models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='会员有效期')),
                ('first_subscription', models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='已订阅过')),
                ('subscription_type', models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=2, verbose_name='订阅状态')),
                ('white_type', models.IntegerField(choices=[(0, '正常'), (1, '拦截')], default=0, verbose_name='白名单')),
                ('flow_user', models.FloatField(blank=True, db_index=True, default=0, verbose_name='已用流量单位GB')),
                ('country', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='国家')),
                ('region', models.CharField(blank=True, max_length=128, null=True, verbose_name='地区')),
                ('adv_count', models.IntegerField(default=0, verbose_name='广告计数')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='登录时间')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPackage', verbose_name='APP平台')),
                ('member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.MembersConfig', verbose_name='APP平台')),
                ('set_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.SetMeal', verbose_name='套餐类型')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User', verbose_name='用户'),
        ),
    ]
