# Generated by Django 2.1.4 on 2021-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210903_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_count',
            field=models.IntegerField(default=0, verbose_name='设备数'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_device_count',
            field=models.IntegerField(default=0, verbose_name='最大设备数'),
        ),
    ]
