# Generated by Django 2.1.4 on 2021-09-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210906_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='package_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, verbose_name='App_id'),
        ),
    ]
