# Generated by Django 2.1.4 on 2021-09-13 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_remove_setmeal_app'),
        ('users', '0005_auto_20210910_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPackage', verbose_name='APP平台'),
        ),
    ]
