# Generated by Django 2.1.4 on 2021-09-13 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app',
        ),
        migrations.AddField(
            model_name='devices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devices',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='登录时间'),
        ),
    ]
