# Generated by Django 2.1.4 on 2021-09-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_remove_setmeal_app'),
        ('users', '0007_auto_20210913_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPlatform', verbose_name='应用平台'),
        ),
    ]
