# Generated by Django 2.1.4 on 2021-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_devices_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
