# Generated by Django 2.1.4 on 2021-09-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210916_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
    ]
