# Generated by Django 2.1.4 on 2021-09-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210918_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='user',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
    ]
