# Generated by Django 2.1.4 on 2021-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210918_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='user',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='用户ID'),
        ),
    ]
