# Generated by Django 2.1.4 on 2021-09-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210918_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True, verbose_name='uuid'),
        ),
    ]
