# Generated by Django 2.1.4 on 2021-11-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210922_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='分享码'),
        ),
    ]
