# Generated by Django 2.1.4 on 2021-11-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='新用户'),
        ),
    ]
