# Generated by Django 2.1.4 on 2021-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exchange',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='兑换'),
        ),
    ]
