# Generated by Django 2.1.4 on 2021-11-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exchange_count',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], db_index=True, default=0, verbose_name='兑换次数'),
        ),
    ]
