# Generated by Django 2.1.4 on 2021-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_exchange_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exchange_count',
            field=models.IntegerField(default=0, verbose_name='兑换次数'),
        ),
    ]
