# Generated by Django 2.1.4 on 2022-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211105_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_validity_time',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='会员有效期'),
        ),
    ]
