# Generated by Django 2.1.4 on 2022-01-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220105_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, '一般'), (2, '重要'), (3, '其他')], default=0, verbose_name='类型')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='邮箱')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
            },
        ),
    ]
