# Generated by Django 2.1.4 on 2022-01-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='uid',
            field=models.BigIntegerField(db_index=True, default=0, unique=True, verbose_name='uid'),
        ),
    ]
