# Generated by Django 2.1.4 on 2022-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userfeedback_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='类型'),
        ),
    ]
