# Generated by Django 2.1.4 on 2022-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220110_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='uid',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='uid'),
        ),
    ]
