# Generated by Django 2.1.4 on 2022-01-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0010_auto_20211227_0614'),
        ('users', '0023_auto_20220111_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShareTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='任务名')),
                ('uid', models.BigIntegerField(db_index=True, default=0, verbose_name='uid')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPackage', verbose_name='APP平台')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPlatform', verbose_name='应用平台')),
            ],
            options={
                'verbose_name': '用户分享任务',
                'verbose_name_plural': '用户分享任务',
            },
        ),
    ]
