# Generated by Django 2.1.4 on 2022-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_usersharetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersharetask',
            name='status',
            field=models.IntegerField(choices=[(0, '未完成'), (1, '完成未领取'), (2, '已领取')], db_index=True, default=0, verbose_name='状态'),
        ),
    ]
