# Generated by Django 2.1.4 on 2022-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_usersharetask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='邮箱'),
        ),
    ]
