# Generated by Django 2.1.4 on 2022-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220301_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='vip_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='会员类型'),
        ),
    ]
