# Generated by Django 2.1.4 on 2021-09-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, '第三方广告'), (2, '诱导付费')], default=1, verbose_name='类型')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='描述')),
                ('skip_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='跳转连接')),
                ('background_image_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='背景图片')),
                ('image_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='图片')),
                ('version', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='版本号')),
                ('induction_pay', models.BooleanField(default=False, verbose_name='诱导付费')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
            options={
                'verbose_name': '广告版本配置',
                'verbose_name_plural': '广告版本配置',
            },
        ),
        migrations.CreateModel(
            name='ApiVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='线上版本号')),
                ('upgrade_version', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='强制升级版本号')),
            ],
            options={
                'verbose_name': '应用版本配置',
                'verbose_name_plural': '应用版本配置',
            },
        ),
        migrations.CreateModel(
            name='AppPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='app名字')),
                ('package_id', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, unique=True, verbose_name='AppID')),
                ('device', models.IntegerField(choices=[(1, 'IOS'), (2, 'Android'), (3, 'PC'), (4, 'MAC')], default=1, verbose_name='设备平台')),
            ],
            options={
                'verbose_name': 'APP',
                'verbose_name_plural': 'APP',
            },
        ),
        migrations.CreateModel(
            name='InduceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='线上版本号')),
                ('json_config', models.TextField(default='', verbose_name='json配置')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.AppPackage', verbose_name='APP_ID')),
            ],
            options={
                'verbose_name': '诱导配置',
                'verbose_name_plural': '诱导配置',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='名字')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
            ],
            options={
                'verbose_name': '会员类型',
                'verbose_name_plural': '会员类型',
            },
        ),
        migrations.CreateModel(
            name='MembersConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('limit_flow', models.IntegerField(default=0, verbose_name='流量限制 单位:G')),
                ('device_count', models.IntegerField(default=0, verbose_name='最大设备数')),
                ('members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.Members', verbose_name='会员类型')),
            ],
            options={
                'verbose_name': '会员配置',
                'verbose_name_plural': '会员配置',
            },
        ),
        migrations.CreateModel(
            name='PayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('buy_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='IOS正式支付url')),
                ('sandbox_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='IOS沙盒url')),
                ('pay_password', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='IOS支付秘钥')),
                ('api_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='谷歌API')),
                ('token_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='谷歌token')),
                ('grant_type', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='谷歌grant_type')),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='谷歌client_id')),
                ('client_secret', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='谷歌client_secret')),
                ('refresh_token', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='谷歌refresh_token')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.AppPackage', verbose_name='APP_ID')),
            ],
            options={
                'verbose_name': '支付配置',
                'verbose_name_plural': '支付配置',
            },
        ),
        migrations.CreateModel(
            name='SetMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品id')),
                ('name', models.CharField(help_text='请输入商品名称', max_length=150, null=True, verbose_name='商品名称')),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='金额')),
                ('day', models.IntegerField(blank=True, default=0, null=True, verbose_name='会员天数')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.AppPackage', verbose_name='APP_ID')),
            ],
            options={
                'verbose_name': '套餐配置',
                'verbose_name_plural': '套餐配置',
            },
        ),
        migrations.CreateModel(
            name='SetMealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='名字')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
            ],
            options={
                'verbose_name': '套餐类型',
                'verbose_name_plural': '套餐类型',
            },
        ),
        migrations.CreateModel(
            name='UsersConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('temp_day', models.IntegerField(default=0, verbose_name='试用天数 单位:天')),
                ('adv_count', models.IntegerField(default=0, verbose_name='广告次数')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.AppPackage', verbose_name='APP平台')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
            },
        ),
        migrations.AddField(
            model_name='setmeal',
            name='set_meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage.SetMealType', verbose_name='套餐类型'),
        ),
        migrations.AddField(
            model_name='apiversion',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.AppPackage', verbose_name='APP_ID'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage.AppPackage', verbose_name='APP_ID'),
        ),
    ]
