# Generated by Django 2.1.4 on 2021-09-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_setmeal_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='payconfig',
            name='test_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='谷歌支付测试ID'),
        ),
    ]
