# Generated by Django 2.1.4 on 2021-09-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_auto_20210910_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersconfig',
            name='app',
        ),
    ]
