# Generated by Django 2.1.4 on 2021-09-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_remove_usersconfig_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmeal',
            name='app',
        ),
    ]
