# Generated by Django 2.1.4 on 2021-11-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_remove_setmeal_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.IntegerField(default=0, verbose_name='分享天数 单位:天')),
            ],
            options={
                'verbose_name': '分享配置',
                'verbose_name_plural': '分享配置',
            },
        ),
    ]
