# Generated by Django 2.1.4 on 2021-12-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0008_shareconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='名称')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
                ('time', models.IntegerField(default=0, verbose_name='时间 单位:秒')),
            ],
            options={
                'verbose_name': '时间配置',
                'verbose_name_plural': '时间配置',
            },
        ),
    ]
