# Generated by Django 2.1.4 on 2021-12-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0009_timeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeconfig',
            name='avd_count',
            field=models.IntegerField(default=0, verbose_name='广告计数 单位：次'),
        ),
        migrations.AlterField(
            model_name='timeconfig',
            name='time',
            field=models.BigIntegerField(default=0, verbose_name='时间 单位:秒'),
        ),
    ]
