# Generated by Django 2.1.4 on 2022-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0010_auto_20211227_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='payconfig',
            name='do_main',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='服务器域名'),
        ),
        migrations.AddField(
            model_name='payconfig',
            name='notify_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='通知url'),
        ),
    ]
