# Generated by Django 2.1.4 on 2022-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0011_auto_20220225_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payconfig',
            name='notify_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ios通知url'),
        ),
    ]
